### ISSUE TITLE
ReferenceError: Rx is not defined

### ISSUE THREAD

**Issue by joshdeese** [richardanaya/rxjs-pubsub#1]
I started a new node project, installed rxjs-pubsub, and copied your code. When I try to run the code I get 

```
/Volumes/Second/node_js/test_pubsub/node_modules/rxjs-pubsub/rxjs-pubsub.js:11
  CustomSubject.prototype = Object.create(Rx.Subject.prototype);
                                          ^
ReferenceError: Rx is not defined
    at /Volumes/Second/node_js/test_pubsub/node_modules/rxjs-pubsub/rxjs-pubsub.js:11:43
    at Object.<anonymous> (/Volumes/Second/node_js/test_pubsub/node_modules/rxjs-pubsub/rxjs-pubsub.js:44:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Volumes/Second/node_js/test_pubsub/main.js:1:76)
    at Module._compile (module.js:456:26)
```

I tried installing rx but it didn't seem to help. Any ideas on what I'm missing?

**Comment by richardanaya** [comment]
Fixed this to work with browser and npm

**Comment by richardanaya** [comment]
Example: http://www.webpackbin.com/VJbZsg9hg
